### ISSUE TITLE
Convert IDL content to mdx

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/design-language-website#1]
Copy over markdown from live site, https://www.ibm.com/design/language/

- [x] Philosophy - Pov 
- [x] Philosophy - Principles
- [ ] Gallery

**Elements**
- [x] Typeface
- [x] Type basics
- [x] Type Specs UI
- [ ] Color
- [ ] Color UI
- [ ] 2x Grid
- [ ] 2x Grid UI
- [ ] Logos - 8 bar
- [ ] Logos - Rebus
- [ ] Icons - Overview
- [ ] Icons - Contribute
- [ ] Icon Librasry
- [ ] App Icons
- [ ] Pictograms - Overview
- [ ] Pictograms - Usage
- [ ] Pictograms - Contribute
- [ ] Photography - Overview
- [ ] Photography - Tips & Techniques
- [ ] Motion - Basics
- [ ] Motion - Choreography
- [ ] Motion - Resources

**Disciplines**
- [x] Product
- [x] Digital

## ToDo

- [ ] Disciplines - Product - Update images 
- [ ] Philosophy - Principles - add custom styles
- [ ] Typeface - missing video component - `typeface_02.mp4`
- [ ] Typeface - type tester styles are broken
- [ ] Type basics - missing video component - `type-basics-comfortable-reading.mp4`
- [ ] Type specs UI - missing video `type-specs-fluid-type.mp4`, missing custom components

**Comment by alisonjoseph** [comment]
Closing, created individual issues for pages
